package com.basic.pojo;

// Generated 2016-6-12 11:03:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer id;
	private String userName;
	private String sex;
	private Date birthday;
	private String degree;
	private String interest;
	private String nonActive;
	private String remark;

	public Student() {
	}

	public Student(String userName, String sex, Date birthday, String degree,
			String interest, String nonActive, String remark) {
		this.userName = userName;
		this.sex = sex;
		this.birthday = birthday;
		this.degree = degree;
		this.interest = interest;
		this.nonActive = nonActive;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getInterest() {
		return this.interest;
	}

	public void setInterest(String interest) {
		this.interest = interest;
	}

	public String getNonActive() {
		return this.nonActive;
	}

	public void setNonActive(String nonActive) {
		this.nonActive = nonActive;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
